// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.12.0
// source: primedecompositionpb/primedecomposition.proto

package primedecompositionpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PrimeDecompose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *PrimeDecompose) Reset() {
	*x = PrimeDecompose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primedecompositionpb_primedecomposition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeDecompose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeDecompose) ProtoMessage() {}

func (x *PrimeDecompose) ProtoReflect() protoreflect.Message {
	mi := &file_primedecompositionpb_primedecomposition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeDecompose.ProtoReflect.Descriptor instead.
func (*PrimeDecompose) Descriptor() ([]byte, []int) {
	return file_primedecompositionpb_primedecomposition_proto_rawDescGZIP(), []int{0}
}

func (x *PrimeDecompose) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type PrimeDecomposeManyTimesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Primedecompose *PrimeDecompose `protobuf:"bytes,1,opt,name=primedecompose,proto3" json:"primedecompose,omitempty"`
}

func (x *PrimeDecomposeManyTimesRequest) Reset() {
	*x = PrimeDecomposeManyTimesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primedecompositionpb_primedecomposition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeDecomposeManyTimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeDecomposeManyTimesRequest) ProtoMessage() {}

func (x *PrimeDecomposeManyTimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_primedecompositionpb_primedecomposition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeDecomposeManyTimesRequest.ProtoReflect.Descriptor instead.
func (*PrimeDecomposeManyTimesRequest) Descriptor() ([]byte, []int) {
	return file_primedecompositionpb_primedecomposition_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeDecomposeManyTimesRequest) GetPrimedecompose() *PrimeDecompose {
	if x != nil {
		return x.Primedecompose
	}
	return nil
}

type PrimeDecomposeManyTimesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PrimeDecomposeManyTimesResponse) Reset() {
	*x = PrimeDecomposeManyTimesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primedecompositionpb_primedecomposition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeDecomposeManyTimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeDecomposeManyTimesResponse) ProtoMessage() {}

func (x *PrimeDecomposeManyTimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_primedecompositionpb_primedecomposition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeDecomposeManyTimesResponse.ProtoReflect.Descriptor instead.
func (*PrimeDecomposeManyTimesResponse) Descriptor() ([]byte, []int) {
	return file_primedecompositionpb_primedecomposition_proto_rawDescGZIP(), []int{2}
}

func (x *PrimeDecomposeManyTimesResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_primedecompositionpb_primedecomposition_proto protoreflect.FileDescriptor

var file_primedecompositionpb_primedecomposition_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x0e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x6c, 0x0a, 0x1e, 0x50, 0x72, 0x69, 0x6d, 0x65,
	0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4a, 0x0a, 0x0e, 0x70, 0x72, 0x69,
	0x6d, 0x65, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x0e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x1f, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0xa0, 0x01, 0x0a, 0x15, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x86, 0x01, 0x0a, 0x17, 0x50,
	0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x4d, 0x61, 0x6e,
	0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x32, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x69, 0x6d,
	0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x70, 0x72, 0x69,
	0x6d, 0x65, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x4d, 0x61,
	0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_primedecompositionpb_primedecomposition_proto_rawDescOnce sync.Once
	file_primedecompositionpb_primedecomposition_proto_rawDescData = file_primedecompositionpb_primedecomposition_proto_rawDesc
)

func file_primedecompositionpb_primedecomposition_proto_rawDescGZIP() []byte {
	file_primedecompositionpb_primedecomposition_proto_rawDescOnce.Do(func() {
		file_primedecompositionpb_primedecomposition_proto_rawDescData = protoimpl.X.CompressGZIP(file_primedecompositionpb_primedecomposition_proto_rawDescData)
	})
	return file_primedecompositionpb_primedecomposition_proto_rawDescData
}

var file_primedecompositionpb_primedecomposition_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_primedecompositionpb_primedecomposition_proto_goTypes = []interface{}{
	(*PrimeDecompose)(nil),                  // 0: primedecomposition.PrimeDecompose
	(*PrimeDecomposeManyTimesRequest)(nil),  // 1: primedecomposition.PrimeDecomposeManyTimesRequest
	(*PrimeDecomposeManyTimesResponse)(nil), // 2: primedecomposition.PrimeDecomposeManyTimesResponse
}
var file_primedecompositionpb_primedecomposition_proto_depIdxs = []int32{
	0, // 0: primedecomposition.PrimeDecomposeManyTimesRequest.primedecompose:type_name -> primedecomposition.PrimeDecompose
	1, // 1: primedecomposition.PrimeDecomposeService.PrimeDecomposeManyTimes:input_type -> primedecomposition.PrimeDecomposeManyTimesRequest
	2, // 2: primedecomposition.PrimeDecomposeService.PrimeDecomposeManyTimes:output_type -> primedecomposition.PrimeDecomposeManyTimesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_primedecompositionpb_primedecomposition_proto_init() }
func file_primedecompositionpb_primedecomposition_proto_init() {
	if File_primedecompositionpb_primedecomposition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_primedecompositionpb_primedecomposition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeDecompose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primedecompositionpb_primedecomposition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeDecomposeManyTimesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primedecompositionpb_primedecomposition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeDecomposeManyTimesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_primedecompositionpb_primedecomposition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_primedecompositionpb_primedecomposition_proto_goTypes,
		DependencyIndexes: file_primedecompositionpb_primedecomposition_proto_depIdxs,
		MessageInfos:      file_primedecompositionpb_primedecomposition_proto_msgTypes,
	}.Build()
	File_primedecompositionpb_primedecomposition_proto = out.File
	file_primedecompositionpb_primedecomposition_proto_rawDesc = nil
	file_primedecompositionpb_primedecomposition_proto_goTypes = nil
	file_primedecompositionpb_primedecomposition_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeDecomposeServiceClient is the client API for PrimeDecomposeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeDecomposeServiceClient interface {
	PrimeDecomposeManyTimes(ctx context.Context, in *PrimeDecomposeManyTimesRequest, opts ...grpc.CallOption) (PrimeDecomposeService_PrimeDecomposeManyTimesClient, error)
}

type primeDecomposeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeDecomposeServiceClient(cc grpc.ClientConnInterface) PrimeDecomposeServiceClient {
	return &primeDecomposeServiceClient{cc}
}

func (c *primeDecomposeServiceClient) PrimeDecomposeManyTimes(ctx context.Context, in *PrimeDecomposeManyTimesRequest, opts ...grpc.CallOption) (PrimeDecomposeService_PrimeDecomposeManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeDecomposeService_serviceDesc.Streams[0], "/primedecomposition.PrimeDecomposeService/PrimeDecomposeManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeDecomposeServicePrimeDecomposeManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeDecomposeService_PrimeDecomposeManyTimesClient interface {
	Recv() (*PrimeDecomposeManyTimesResponse, error)
	grpc.ClientStream
}

type primeDecomposeServicePrimeDecomposeManyTimesClient struct {
	grpc.ClientStream
}

func (x *primeDecomposeServicePrimeDecomposeManyTimesClient) Recv() (*PrimeDecomposeManyTimesResponse, error) {
	m := new(PrimeDecomposeManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeDecomposeServiceServer is the server API for PrimeDecomposeService service.
type PrimeDecomposeServiceServer interface {
	PrimeDecomposeManyTimes(*PrimeDecomposeManyTimesRequest, PrimeDecomposeService_PrimeDecomposeManyTimesServer) error
}

// UnimplementedPrimeDecomposeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeDecomposeServiceServer struct {
}

func (*UnimplementedPrimeDecomposeServiceServer) PrimeDecomposeManyTimes(*PrimeDecomposeManyTimesRequest, PrimeDecomposeService_PrimeDecomposeManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeDecomposeManyTimes not implemented")
}

func RegisterPrimeDecomposeServiceServer(s *grpc.Server, srv PrimeDecomposeServiceServer) {
	s.RegisterService(&_PrimeDecomposeService_serviceDesc, srv)
}

func _PrimeDecomposeService_PrimeDecomposeManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeDecomposeManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeDecomposeServiceServer).PrimeDecomposeManyTimes(m, &primeDecomposeServicePrimeDecomposeManyTimesServer{stream})
}

type PrimeDecomposeService_PrimeDecomposeManyTimesServer interface {
	Send(*PrimeDecomposeManyTimesResponse) error
	grpc.ServerStream
}

type primeDecomposeServicePrimeDecomposeManyTimesServer struct {
	grpc.ServerStream
}

func (x *primeDecomposeServicePrimeDecomposeManyTimesServer) Send(m *PrimeDecomposeManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeDecomposeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "primedecomposition.PrimeDecomposeService",
	HandlerType: (*PrimeDecomposeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeDecomposeManyTimes",
			Handler:       _PrimeDecomposeService_PrimeDecomposeManyTimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "primedecompositionpb/primedecomposition.proto",
}
