# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: practice/practice_packg/building.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from practice.practice_packg import street_imp_pb2 as practice_dot_practice__packg_dot_street__imp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='practice/practice_packg/building.proto',
  package='my.building',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&practice/practice_packg/building.proto\x12\x0bmy.building\x1a(practice/practice_packg/street_imp.proto\"]\n\x08\x42uilding\x12\x15\n\rbuilding_name\x18\x01 \x01(\t\x12\x17\n\x0f\x62uilding_number\x18\x02 \x01(\x05\x12!\n\x06street\x18\x03 \x01(\x0b\x32\x11.my.street.Streetb\x06proto3'
  ,
  dependencies=[practice_dot_practice__packg_dot_street__imp__pb2.DESCRIPTOR,])




_BUILDING = _descriptor.Descriptor(
  name='Building',
  full_name='my.building.Building',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='building_name', full_name='my.building.Building.building_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='building_number', full_name='my.building.Building.building_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='street', full_name='my.building.Building.street', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=190,
)

_BUILDING.fields_by_name['street'].message_type = practice_dot_practice__packg_dot_street__imp__pb2._STREET
DESCRIPTOR.message_types_by_name['Building'] = _BUILDING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Building = _reflection.GeneratedProtocolMessageType('Building', (_message.Message,), {
  'DESCRIPTOR' : _BUILDING,
  '__module__' : 'practice.practice_packg.building_pb2'
  # @@protoc_insertion_point(class_scope:my.building.Building)
  })
_sym_db.RegisterMessage(Building)


# @@protoc_insertion_point(module_scope)
