# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: practice/practice_packg/street_imp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from practice.practice_packg import city_imp_pb2 as practice_dot_practice__packg_dot_city__imp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='practice/practice_packg/street_imp.proto',
  package='my.street',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(practice/practice_packg/street_imp.proto\x12\tmy.street\x1a&practice/practice_packg/city_imp.proto\":\n\x06Street\x12\x13\n\x0bstreet_name\x18\x01 \x01(\t\x12\x1b\n\x04\x63ity\x18\x02 \x01(\x0b\x32\r.my.city.Cityb\x06proto3'
  ,
  dependencies=[practice_dot_practice__packg_dot_city__imp__pb2.DESCRIPTOR,])




_STREET = _descriptor.Descriptor(
  name='Street',
  full_name='my.street.Street',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='street_name', full_name='my.street.Street.street_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='city', full_name='my.street.Street.city', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=153,
)

_STREET.fields_by_name['city'].message_type = practice_dot_practice__packg_dot_city__imp__pb2._CITY
DESCRIPTOR.message_types_by_name['Street'] = _STREET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Street = _reflection.GeneratedProtocolMessageType('Street', (_message.Message,), {
  'DESCRIPTOR' : _STREET,
  '__module__' : 'practice.practice_packg.street_imp_pb2'
  # @@protoc_insertion_point(class_scope:my.street.Street)
  })
_sym_db.RegisterMessage(Street)


# @@protoc_insertion_point(module_scope)
